-   id: Autodoc-hook
    name: Autodoc-hook
    description: This hook automatically documents python functions and methods with docstrings.
    entry: Autodoc-hook
    language: python
    types: [python]
    files: ''
